server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: java-service
          uri:  https://nhom5-project4-chieut6-1.onrender.com
          predicates:
            - Path=/api/java/**
          filters:
            - StripPrefix=2

        - id: spring-service
          uri: https://api-backend-spring-nhom5-chieut6.onrender.com
          predicates:
            - Path=/api/spring/**
          filters:
            - StripPrefix=2

        - id: node-service
          uri: https://api-backend-node-nhom5-chieut6.onrender.com
          predicates:
            - Path=/api/node/**
          filters:
            - StripPrefix=2
        - id: test-google
          uri: https://www.google.com
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1
        
        
