# 1. Đường dẫn Database (Tuyệt đối không có username:password@ ở đây)
spring.datasource.url=jdbc:postgresql://dpg-d7gdfom7r5hc73d5n0v0-a.singapore-postgres.render.com/nhom5_thu6_xcbm?sslmode=require

# 2. Tài khoản
spring.datasource.username=nhom5_thu6_xcbm_user

# 3. Mật khẩu
spring.datasource.password=wHkaImVopwIIQ35sDwo5Cn0vTj4JozAp

# 4. Cấu hình JPA tự động tạo bảng
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.profiles.active=seed-data

aws.access-key=AKIATT3THGEFT466UC6J
aws.secret-key=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

aws.region=ap-southeast-1

aws.s3.bucket=diem-danh-bang-khuon-mat-2
aws.rekognition.collection=students_faces

jwt.secret.key=Nhom5Thu6SecretKeyNhom5Thu6SecretKeyNhom5Thu6SecretKey
jwt.expiration.millis=86400000