/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.sun.net.httpserver.HttpServer;
import com.sun.net.httpserver.HttpHandler;
import com.sun.net.httpserver.HttpExchange;
import java.io.IOException;
import java.io.OutputStream;
import java.net.InetSocketAddress;
import java.sql.*;

public class App {
    private static final String DB_URL = "jdbc:postgresql://dpg-d6pclluuk2gs73crsds0-a.singapore-postgres.render.com:5432/nhom5_thu6";
    private static final String DB_USER = "nhom5_thu6_user";
    private static final String DB_PASS = "mPc8oHzzBzWOQTYjx2QNStuiWwRZz1Bi";

    public static void main(String[] args) throws IOException {
        String portEnv = System.getenv("PORT");
        int port = (portEnv != null) ? Integer.parseInt(portEnv) : 8080;

        HttpServer server = HttpServer.create(new InetSocketAddress(port), 0);
        server.createContext("/", new UsersHandler());
        server.setExecutor(null);
        server.start();

        System.out.println("API Server đang chạy ở port: " + port);
    }

    static class UsersHandler implements HttpHandler {
        @Override
        public void handle(HttpExchange t) throws IOException {
            t.getResponseHeaders().add("Content-Type", "application/json; charset=UTF-8");
            String response;
            int statusCode = 200;

            try {
                response = getUsersFromDatabase();
            } catch (Exception e) {
                statusCode = 500;
                response = "{\"error\": \"" + e.getMessage() + "\"}";
                e.printStackTrace();
            }

            byte[] bytes = response.getBytes("UTF-8");
            t.sendResponseHeaders(statusCode, bytes.length);
            try (OutputStream os = t.getResponseBody()) {
                os.write(bytes);
            }
        }
    }

    private static String getUsersFromDatabase() throws SQLException {
        StringBuilder json = new StringBuilder();
        json.append("[");

        if (DB_URL == null)
            return "[{\"message\": \"Chưa có kết nối DB\"}]";

        try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASS);
                Statement stmt = conn.createStatement();
                ResultSet rs = stmt.executeQuery("SELECT id, name, mssv FROM users")) {

            boolean first = true;
            while (rs.next()) {
                if (!first)
                    json.append(",");
                json.append("{")
                        .append("\"id\":").append(rs.getInt("id")).append(",")
                        .append("\"name\":\"").append(rs.getString("name")).append("\",")
                        .append("\"mssv\":\"").append(rs.getString("mssv")).append("\"")
                        .append("}");
                first = false;
            }
        }
        json.append("]");
        return json.toString();
    }
}